version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: devops_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devops_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devops_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
